export default {content: [
  './index.html',
  './src/**/*.{js,ts,jsx,tsx}'
],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        display: ['Sora', 'system-ui', 'sans-serif'],
        sans: ['"DM Sans"', 'Poppins', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        serif: ['Georgia', 'serif'],
        orbitron: ['Orbitron', 'monospace', 'sans-serif'],
        poppins: ['Poppins', '"DM Sans"', 'sans-serif'],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
      },
      colors: {
        quanta: {
          purple: '#4c1d70',
          'purple-dark': '#361452',
          'purple-deep': '#240b38',
          'purple-light': '#6a289d',
          gold: '#f5d626',
          'gold-hover': '#e2c317',
          'gold-light': '#ffeb60',
          teal: '#00b294',
          'teal-light': '#10b981',
        },
        brand: {
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
        },
      },
      fontSize: {
        display: ['3.5rem', { lineHeight: '1.08', letterSpacing: '-0.025em' }],
        h1: ['2.25rem', { lineHeight: '1.18', letterSpacing: '-0.02em' }],
        h2: ['1.45rem', { lineHeight: '1.25', letterSpacing: '-0.01em' }],
        h3: ['1.18rem', { lineHeight: '1.32', letterSpacing: '-0.005em' }],
        body: ['1rem', { lineHeight: '1.68' }],
        label: ['0.8125rem', { lineHeight: '1.25', letterSpacing: '0.06em' }],
        xs: ['0.8125rem', { lineHeight: '1.25rem' }],
        sm: ['0.9375rem', { lineHeight: '1.45rem' }],
        base: ['1.05rem', { lineHeight: '1.65rem' }],
        lg: ['1.1875rem', { lineHeight: '1.75rem' }],
        xl: ['1.3125rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.625rem', { lineHeight: '2rem' }],
        '3xl': ['2rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.375rem', { lineHeight: '2.5rem' }],
      },
      keyframes: {
        'marquee-left': {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        'marquee-right': {
          '0%': { transform: 'translateX(-50%)' },
          '100%': { transform: 'translateX(0%)' },
        },
        fadeInUp: {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        scalePulse: {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.04)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        laserSweep: {
          '0%': { left: '0%', opacity: '0' },
          '15%': { opacity: '1' },
          '85%': { opacity: '1' },
          '100%': { left: '100%', opacity: '0' },
        },
        goldAura: {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(245, 214, 38, 0.4)' },
          '50%': { boxShadow: '0 0 0 10px rgba(245, 214, 38, 0)' },
        },
      },
      animation: {
        'marquee-left': 'marquee-left 40s linear infinite',
        'marquee-right': 'marquee-right 40s linear infinite',
        'fade-in-up': 'fadeInUp 0.3s ease-out',
        fadeInUp: 'fadeInUp 0.3s ease-out',
        scalePulse: 'scalePulse 2s ease-in-out infinite',
        'scale-pulse': 'scalePulse 2s ease-in-out infinite',
        shimmer: 'shimmer 3s ease-in-out infinite',
        laserSweep: 'laserSweep 2.2s cubic-bezier(0.4, 0, 0.2, 1) infinite',
        goldAura: 'goldAura 2.2s infinite',
      },
    },
  },
}
