from enum import Enum


class AchievementCategory(str, Enum):
    ONBOARDING = "ONBOARDING"
    STREAK = "STREAK"
    MASTERY = "MASTERY"
    FOCUS = "FOCUS"
    QUANTUM_LAB = "QUANTUM_LAB"
    EXPLORER = "EXPLORER"


class XPEventType(str, Enum):
    LESSON_COMPLETE = "LESSON_COMPLETE"           # +50 XP
    QUIZ_PASSED = "QUIZ_PASSED"                   # +100 XP
    DIAGNOSTIC_COMPLETE = "DIAGNOSTIC_COMPLETE"   # +150 XP
    STREAK_MAINTAINED = "STREAK_MAINTAINED"       # +25 XP
    FOCUS_SESSION_DONE = "FOCUS_SESSION_DONE"     # +40 XP
    CIRCUIT_EXECUTED = "CIRCUIT_EXECUTED"         # +60 XP
    ACHIEVEMENT_UNLOCKED = "ACHIEVEMENT_UNLOCKED" # +100 XP
