from enum import Enum


class MascotState(str, Enum):
    """Canonical 18 Qubot states defined in Section 12, with legacy aliases."""
    IDLE = "IDLE"
    GREETING = "GREETING"
    LISTENING = "LISTENING"
    THINKING = "THINKING"
    WATCHING = "WATCHING"
    ENCOURAGING = "ENCOURAGING"
    CELEBRATING = "CELEBRATING"
    CONFUSED = "CONFUSED"
    CONCERNED = "CONCERNED"
    HELPING = "HELPING"
    EXPLAINING = "EXPLAINING"
    HINTING = "HINTING"
    WAITING = "WAITING"
    BREAK_SUGGESTED = "BREAK_SUGGESTED"
    BREAK_ACTIVE = "BREAK_ACTIVE"
    BREAK_REQUIRED = "BREAK_REQUIRED"
    DISTRACTION_INTERVENTION = "DISTRACTION_INTERVENTION"
    SESSION_COMPLETE = "SESSION_COMPLETE"

    # Backward compatibility aliases
    HAPPY = "CELEBRATING"
    FOCUS_REMINDER = "ENCOURAGING"
    BREAK_REMINDER = "BREAK_SUGGESTED"
    SLEEPING = "IDLE"
