from enum import Enum


class QUBOTState(str, Enum):
    """18 Canonical Qubot States defined in Section 12."""
    IDLE = "IDLE"
    GREETING = "GREETING"
    LISTENING = "LISTENING"
    THINKING = "THINKING"
    WATCHING = "WATCHING"
    ENCOURAGING = "ENCOURAGING"
    CELEBRATING = "CELEBRATING"
    CONFUSED = "CONFUSED"
    CONCERNED = "CONCERNED"
    HELPING = "HELPING"
    EXPLAINING = "EXPLAINING"
    HINTING = "HINTING"
    WAITING = "WAITING"
    BREAK_SUGGESTED = "BREAK_SUGGESTED"
    BREAK_ACTIVE = "BREAK_ACTIVE"
    BREAK_REQUIRED = "BREAK_REQUIRED"
    DISTRACTION_INTERVENTION = "DISTRACTION_INTERVENTION"
    SESSION_COMPLETE = "SESSION_COMPLETE"


class QUBOTEmotion(str, Enum):
    """12 Canonical Emotions defined in Section 13 (separate from state)."""
    NEUTRAL = "NEUTRAL"
    CURIOUS = "CURIOUS"
    HAPPY = "HAPPY"
    EXCITED = "EXCITED"
    PROUD = "PROUD"
    SUPPORTIVE = "SUPPORTIVE"
    CONCERNED = "CONCERNED"
    THOUGHTFUL = "THOUGHTFUL"
    ENCOURAGING = "ENCOURAGING"
    PLAYFUL = "PLAYFUL"
    CALM = "CALM"
    FOCUSED = "FOCUSED"


class QUBOTAnimation(str, Enum):
    """Semantic Animation Identifiers defined in Section 14."""
    IDLE_BREATHE = "idle_breathe"
    LOOK_LEFT = "look_left"
    LOOK_RIGHT = "look_right"
    THINK = "think"
    SMALL_HAPPY = "small_happy"
    CELEBRATE = "celebrate"
    GENTLE_ENCOURAGE = "gentle_encourage"
    CONCERNED = "concerned"
    HINT = "hint"
    EXPLAIN = "explain"
    LISTEN = "listen"
    BREAK_SUGGEST = "break_suggest"
    SLEEPY = "sleepy"
    FOCUS = "focus"
    WAVE = "wave"


class StruggleType(str, Enum):
    """Struggle Classifications defined in Section 8."""
    NONE = "NONE"
    CONCEPTUAL = "CONCEPTUAL"
    PROCEDURAL = "PROCEDURAL"
    REPEATED_ERROR = "REPEATED_ERROR"
    TIME_PRESSURE = "TIME_PRESSURE"
    GUESSING = "GUESSING"
    FATIGUE = "FATIGUE"
    DISTRACTION = "DISTRACTION"
    DIFFICULTY_MISMATCH = "DIFFICULTY_MISMATCH"
    UNKNOWN = "UNKNOWN"


class StruggleSeverity(str, Enum):
    """Struggle Threshold Levels defined in Section 9."""
    NORMAL = "NORMAL"        # 0.00 - 0.29
    MILD = "MILD"            # 0.30 - 0.49
    MODERATE = "MODERATE"    # 0.50 - 0.69
    HIGH = "HIGH"            # 0.70 - 0.84
    CRITICAL = "CRITICAL"    # 0.85 - 1.00


class InterventionType(str, Enum):
    """Intervention Actions defined in Section 10."""
    NONE = "NONE"
    ALTERNATIVE_EXPLANATION = "ALTERNATIVE_EXPLANATION"
    STEP_BY_STEP_HINT = "STEP_BY_STEP_HINT"
    SLOW_DOWN_PROMPT = "SLOW_DOWN_PROMPT"
    BREAK_SUGGESTION = "BREAK_SUGGESTION"
    DISTRACTION_RESET = "DISTRACTION_RESET"
    RECOMMEND_PREREQUISITE = "RECOMMEND_PREREQUISITE"
    MISTAKE_ANALYSIS = "MISTAKE_ANALYSIS"
    REASSURANCE = "REASSURANCE"


class QUBOTIntent(str, Enum):
    """Message and Dialogue Intents defined in Section 15."""
    WELCOME = "WELCOME"
    ENCOURAGE = "ENCOURAGE"
    CORRECT_ANSWER = "CORRECT_ANSWER"
    INCORRECT_ANSWER = "INCORRECT_ANSWER"
    CONCEPTUAL_HELP = "CONCEPTUAL_HELP"
    REPEATED_ERROR_HELP = "REPEATED_ERROR_HELP"
    HINT_OFFER = "HINT_OFFER"
    ALTERNATIVE_EXPLANATION = "ALTERNATIVE_EXPLANATION"
    GUESSING_WARNING = "GUESSING_WARNING"
    BREAK_SUGGESTION = "BREAK_SUGGESTION"
    BREAK_REQUIRED = "BREAK_REQUIRED"
    BREAK_COMPLETE = "BREAK_COMPLETE"
    SESSION_RESUME = "SESSION_RESUME"
    MILESTONE = "MILESTONE"
    LESSON_COMPLETE = "LESSON_COMPLETE"
    GOODBYE = "GOODBYE"
    # Legacy aliases
    ONBOARDING_GUIDE = "WELCOME"
    LESSON_INTRO = "WELCOME"
    LEARNING_ENCOURAGEMENT = "ENCOURAGE"
    HINT = "HINT_OFFER"
    ASSESSMENT_ENCOURAGEMENT = "ENCOURAGE"
    ASSESSMENT_SUCCESS = "CORRECT_ANSWER"
    ASSESSMENT_REINFORCEMENT = "INCORRECT_ANSWER"
    REVISION_RECOMMENDATION = "CONCEPTUAL_HELP"
    TOPIC_MASTERED = "MILESTONE"
    LEVEL_UP = "MILESTONE"
    ACHIEVEMENT_UNLOCKED = "MILESTONE"
    STREAK_MILESTONE = "MILESTONE"
    NEXT_RECOMMENDATION = "ENCOURAGE"
    FOCUS_START = "SESSION_RESUME"
    FOCUS_ENCOURAGEMENT = "ENCOURAGE"
    FOCUS_REMINDER = "ENCOURAGE"
    BREAK_RECOMMENDATION = "BREAK_SUGGESTION"
    BREAK_SKIPPED = "SESSION_RESUME"
    BREAK_COMPLETED = "BREAK_COMPLETE"
    DISTRACTION_REMINDER = "GUESSING_WARNING"
    USER_RETURNED = "SESSION_RESUME"
    CLARIFICATION = "CONCEPTUAL_HELP"
    ERROR = "GOODBYE"


class QUBOTActionType(str, Enum):
    NONE = "NONE"
    OPEN_LESSON = "OPEN_LESSON"
    OPEN_REVISION = "OPEN_REVISION"
    OPEN_ASSESSMENT = "OPEN_ASSESSMENT"
    START_FOCUS = "START_FOCUS"
    START_BREAK = "START_BREAK"
    OPEN_PROGRESS = "OPEN_PROGRESS"
    OPEN_ACHIEVEMENTS = "OPEN_ACHIEVEMENTS"
    CONTINUE_LEARNING = "CONTINUE_LEARNING"
    VIEW_RECOMMENDATION = "VIEW_RECOMMENDATION"
    RESUME_LEARNING = "RESUME_LEARNING"
    START_RESET = "START_RESET"
    OPEN_ALTERNATIVE_EXPLANATION = "OPEN_ALTERNATIVE_EXPLANATION"
    DISMISS = "DISMISS"


class QUBOTPriority(str, Enum):
    LOW = "LOW"
    NORMAL = "NORMAL"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class QUBOTTone(str, Enum):
    PLAYFUL = "PLAYFUL"
    BALANCED = "BALANCED"
    PROFESSIONAL = "PROFESSIONAL"
    SUPPORTIVE = "SUPPORTIVE"


class QUBOTAnimationLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class QUBOTEventCatalog(str, Enum):
    """Normalized Event Catalog defined in Section 4."""
    SESSION_STARTED = "SESSION_STARTED"
    SESSION_RESUMED = "SESSION_RESUMED"
    SESSION_PAUSED = "SESSION_PAUSED"
    SESSION_ENDED = "SESSION_ENDED"

    LESSON_STARTED = "LESSON_STARTED"
    LESSON_COMPLETED = "LESSON_COMPLETED"
    TOPIC_STARTED = "TOPIC_STARTED"
    TOPIC_COMPLETED = "TOPIC_COMPLETED"

    QUESTION_STARTED = "QUESTION_STARTED"
    ANSWER_SUBMITTED = "ANSWER_SUBMITTED"
    ANSWER_CORRECT = "ANSWER_CORRECT"
    ANSWER_WRONG = "ANSWER_WRONG"

    HINT_REQUESTED = "HINT_REQUESTED"
    EXPLANATION_REQUESTED = "EXPLANATION_REQUESTED"
    SOLUTION_VIEWED = "SOLUTION_VIEWED"

    MULTIPLE_ATTEMPTS = "MULTIPLE_ATTEMPTS"
    LONG_INACTIVITY = "LONG_INACTIVITY"
    RAPID_GUESSING = "RAPID_GUESSING"
    REPEATED_CONCEPT_FAILURE = "REPEATED_CONCEPT_FAILURE"

    MASTERY_INCREASED = "MASTERY_INCREASED"
    MASTERY_DECREASED = "MASTERY_DECREASED"
    MILESTONE_REACHED = "MILESTONE_REACHED"

    POMODORO_STARTED = "POMODORO_STARTED"
    POMODORO_COMPLETED = "POMODORO_COMPLETED"
    BREAK_SUGGESTED = "BREAK_SUGGESTED"
    BREAK_ACCEPTED = "BREAK_ACCEPTED"
    BREAK_SKIPPED = "BREAK_SKIPPED"
    BREAK_STARTED = "BREAK_STARTED"
    BREAK_COMPLETED = "BREAK_COMPLETED"
    BREAK_REQUIRED = "BREAK_REQUIRED"

    QUBOT_OPENED = "QUBOT_OPENED"
    QUBOT_INTERACTION = "QUBOT_INTERACTION"
    QUBOT_DISMISSED = "QUBOT_DISMISSED"
    QUBOT_INTERVENTION_ACCEPTED = "QUBOT_INTERVENTION_ACCEPTED"
    QUBOT_INTERVENTION_REJECTED = "QUBOT_INTERVENTION_REJECTED"
